#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_let = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_in = 4,
  anon_sym_EQ = 5,
  sym_input = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_DOT = 9,
  aux_sym_path_seg_token1 = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_string_token1 = 12,
  anon_sym_DASH = 13,
  aux_sym_float_token1 = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  sym_null = 17,
  anon_sym_DOT_DOT = 18,
  sym_comment = 19,
  sym_source_file = 20,
  sym_assign_block = 21,
  sym_assignment = 22,
  sym_value = 23,
  sym_object = 24,
  sym__object_value = 25,
  sym_array = 26,
  sym__array_value = 27,
  sym_pair = 28,
  sym_path = 29,
  sym_path_seg = 30,
  sym_string = 31,
  sym_float = 32,
  sym_integer = 33,
  sym_boolean = 34,
  sym_spread = 35,
  aux_sym_assign_block_repeat1 = 36,
  aux_sym_object_repeat1 = 37,
  aux_sym_array_repeat1 = 38,
  aux_sym_path_repeat1 = 39,
  aux_sym_path_seg_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_EQ] = "=",
  [sym_input] = "input",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [aux_sym_path_seg_token1] = "path_seg_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_float_token1] = "float_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT_DOT] = "..",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_assign_block] = "assign_block",
  [sym_assignment] = "assignment",
  [sym_value] = "value",
  [sym_object] = "object",
  [sym__object_value] = "_object_value",
  [sym_array] = "array",
  [sym__array_value] = "_array_value",
  [sym_pair] = "pair",
  [sym_path] = "path",
  [sym_path_seg] = "path_seg",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_boolean] = "boolean",
  [sym_spread] = "spread",
  [aux_sym_assign_block_repeat1] = "assign_block_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_path_seg_repeat1] = "path_seg_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_input] = sym_input,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_path_seg_token1] = aux_sym_path_seg_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_assign_block] = sym_assign_block,
  [sym_assignment] = sym_assignment,
  [sym_value] = sym_value,
  [sym_object] = sym_object,
  [sym__object_value] = sym__object_value,
  [sym_array] = sym_array,
  [sym__array_value] = sym__array_value,
  [sym_pair] = sym_pair,
  [sym_path] = sym_path,
  [sym_path_seg] = sym_path_seg,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_boolean] = sym_boolean,
  [sym_spread] = sym_spread,
  [aux_sym_assign_block_repeat1] = aux_sym_assign_block_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_path_seg_repeat1] = aux_sym_path_seg_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_seg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym__object_value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_value] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_seg] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_spread] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_assign_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_seg_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 11,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 9,
  [33] = 33,
  [34] = 10,
  [35] = 15,
  [36] = 36,
  [37] = 37,
  [38] = 14,
  [39] = 18,
  [40] = 20,
  [41] = 41,
  [42] = 17,
  [43] = 12,
  [44] = 13,
  [45] = 45,
  [46] = 19,
  [47] = 16,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 52,
  [65] = 65,
  [66] = 66,
  [67] = 63,
  [68] = 68,
  [69] = 51,
  [70] = 55,
  [71] = 62,
  [72] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 17:
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '$') ADVANCE(17);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(19)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(43);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\r' ||
          lookahead == '"') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 19},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 19},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 19},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 19},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 19},
  [29] = {.lex_state = 19},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 19},
  [50] = {.lex_state = 19},
  [51] = {.lex_state = 19},
  [52] = {.lex_state = 19},
  [53] = {.lex_state = 19},
  [54] = {.lex_state = 19},
  [55] = {.lex_state = 19},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 19},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 34},
  [60] = {.lex_state = 19},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 19},
  [63] = {.lex_state = 19},
  [64] = {.lex_state = 19},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 19},
  [67] = {.lex_state = 19},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 19},
  [70] = {.lex_state = 19},
  [71] = {.lex_state = 19},
  [72] = {.lex_state = 34},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_path_seg_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(68),
    [sym_assign_block] = STATE(50),
    [sym_object] = STATE(65),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_value] = STATE(6),
    [sym_object] = STATE(18),
    [sym_array] = STATE(18),
    [sym__array_value] = STATE(6),
    [sym_string] = STATE(18),
    [sym_float] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_spread] = STATE(6),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_input] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(9),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_value] = STATE(5),
    [sym_object] = STATE(18),
    [sym_array] = STATE(18),
    [sym__array_value] = STATE(5),
    [sym_string] = STATE(18),
    [sym_float] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_spread] = STATE(5),
    [aux_sym_array_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_input] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(9),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_value] = STATE(2),
    [sym_object] = STATE(18),
    [sym_array] = STATE(18),
    [sym__array_value] = STATE(2),
    [sym_string] = STATE(18),
    [sym_float] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_spread] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_input] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(9),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_value] = STATE(6),
    [sym_object] = STATE(18),
    [sym_array] = STATE(18),
    [sym__array_value] = STATE(6),
    [sym_string] = STATE(18),
    [sym_float] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_spread] = STATE(6),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_input] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [aux_sym_float_token1] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_null] = ACTIONS(9),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_value] = STATE(6),
    [sym_object] = STATE(18),
    [sym_array] = STATE(18),
    [sym__array_value] = STATE(6),
    [sym_string] = STATE(18),
    [sym_float] = STATE(18),
    [sym_integer] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_spread] = STATE(6),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(31),
    [sym_input] = ACTIONS(34),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(40),
    [anon_sym_DQUOTE] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(45),
    [aux_sym_float_token1] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_null] = ACTIONS(34),
    [anon_sym_DOT_DOT] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    STATE(49), 1,
      sym_value,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      anon_sym_DASH,
    ACTIONS(67), 1,
      aux_sym_float_token1,
    STATE(36), 1,
      sym_value,
    ACTIONS(59), 2,
      sym_input,
      sym_null,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [76] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DOT,
    ACTIONS(71), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [97] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(77), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      aux_sym_float_token1,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [299] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 1,
      aux_sym_path_seg_token1,
    ACTIONS(103), 1,
      anon_sym_DOT_DOT,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(33), 1,
      sym_path_seg,
    STATE(61), 1,
      sym_path,
    STATE(25), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [327] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_path_seg_token1,
    ACTIONS(103), 1,
      anon_sym_DOT_DOT,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(33), 1,
      sym_path_seg,
    STATE(61), 1,
      sym_path,
    STATE(24), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [355] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(109), 1,
      aux_sym_path_seg_token1,
    ACTIONS(112), 1,
      anon_sym_DOT_DOT,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(33), 1,
      sym_path_seg,
    STATE(61), 1,
      sym_path,
    STATE(23), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [383] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_path_seg_token1,
    ACTIONS(103), 1,
      anon_sym_DOT_DOT,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(33), 1,
      sym_path_seg,
    STATE(61), 1,
      sym_path,
    STATE(23), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [411] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_path_seg_token1,
    ACTIONS(103), 1,
      anon_sym_DOT_DOT,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(33), 1,
      sym_path_seg,
    STATE(61), 1,
      sym_path,
    STATE(23), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(121), 1,
      sym_input,
    STATE(29), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [453] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_DOT,
    ACTIONS(125), 1,
      aux_sym_path_seg_token1,
    ACTIONS(77), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [467] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_input,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [481] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      sym_input,
    STATE(29), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [495] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      aux_sym_path_seg_token1,
    STATE(31), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(134), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [509] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      aux_sym_path_seg_token1,
    STATE(31), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(138), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [523] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_DOT,
    ACTIONS(145), 1,
      aux_sym_path_seg_token1,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [537] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_EQ,
    ACTIONS(149), 1,
      anon_sym_DOT,
    STATE(45), 1,
      aux_sym_path_repeat1,
  [550] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_path_seg_token1,
    ACTIONS(75), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [561] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      aux_sym_path_seg_token1,
    ACTIONS(87), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [572] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      aux_sym_path_seg_token1,
    ACTIONS(155), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [583] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_EQ,
    ACTIONS(161), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_path_repeat1,
  [596] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      aux_sym_path_seg_token1,
    ACTIONS(85), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [607] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      aux_sym_path_seg_token1,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      aux_sym_path_seg_token1,
    ACTIONS(97), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_path_seg_token1,
    STATE(30), 1,
      aux_sym_path_seg_repeat1,
    STATE(48), 1,
      sym_path_seg,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      aux_sym_path_seg_token1,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [653] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      aux_sym_path_seg_token1,
    ACTIONS(81), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [664] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      aux_sym_path_seg_token1,
    ACTIONS(83), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [675] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_EQ,
    STATE(37), 1,
      aux_sym_path_repeat1,
  [688] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      aux_sym_path_seg_token1,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      aux_sym_path_seg_token1,
    ACTIONS(89), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_RBRACE,
      sym_input,
  [726] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_object,
  [736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
  [743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_input,
  [750] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
  [757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_in,
  [764] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      aux_sym_float_token1,
  [771] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_EQ,
  [778] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_in,
  [785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
  [792] = 2,
    ACTIONS(200), 1,
      aux_sym_string_token1,
    ACTIONS(202), 1,
      sym_comment,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_EQ,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_float_token1,
  [820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      aux_sym_float_token1,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_input,
  [834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LBRACE,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      aux_sym_float_token1,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      aux_sym_float_token1,
  [876] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      aux_sym_float_token1,
  [883] = 2,
    ACTIONS(202), 1,
      sym_comment,
    ACTIONS(228), 1,
      aux_sym_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 38,
  [SMALL_STATE(9)] = 76,
  [SMALL_STATE(10)] = 97,
  [SMALL_STATE(11)] = 116,
  [SMALL_STATE(12)] = 137,
  [SMALL_STATE(13)] = 156,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 192,
  [SMALL_STATE(16)] = 210,
  [SMALL_STATE(17)] = 228,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 299,
  [SMALL_STATE(22)] = 327,
  [SMALL_STATE(23)] = 355,
  [SMALL_STATE(24)] = 383,
  [SMALL_STATE(25)] = 411,
  [SMALL_STATE(26)] = 439,
  [SMALL_STATE(27)] = 453,
  [SMALL_STATE(28)] = 467,
  [SMALL_STATE(29)] = 481,
  [SMALL_STATE(30)] = 495,
  [SMALL_STATE(31)] = 509,
  [SMALL_STATE(32)] = 523,
  [SMALL_STATE(33)] = 537,
  [SMALL_STATE(34)] = 550,
  [SMALL_STATE(35)] = 561,
  [SMALL_STATE(36)] = 572,
  [SMALL_STATE(37)] = 583,
  [SMALL_STATE(38)] = 596,
  [SMALL_STATE(39)] = 607,
  [SMALL_STATE(40)] = 618,
  [SMALL_STATE(41)] = 629,
  [SMALL_STATE(42)] = 642,
  [SMALL_STATE(43)] = 653,
  [SMALL_STATE(44)] = 664,
  [SMALL_STATE(45)] = 675,
  [SMALL_STATE(46)] = 688,
  [SMALL_STATE(47)] = 699,
  [SMALL_STATE(48)] = 710,
  [SMALL_STATE(49)] = 718,
  [SMALL_STATE(50)] = 726,
  [SMALL_STATE(51)] = 736,
  [SMALL_STATE(52)] = 743,
  [SMALL_STATE(53)] = 750,
  [SMALL_STATE(54)] = 757,
  [SMALL_STATE(55)] = 764,
  [SMALL_STATE(56)] = 771,
  [SMALL_STATE(57)] = 778,
  [SMALL_STATE(58)] = 785,
  [SMALL_STATE(59)] = 792,
  [SMALL_STATE(60)] = 799,
  [SMALL_STATE(61)] = 806,
  [SMALL_STATE(62)] = 813,
  [SMALL_STATE(63)] = 820,
  [SMALL_STATE(64)] = 827,
  [SMALL_STATE(65)] = 834,
  [SMALL_STATE(66)] = 841,
  [SMALL_STATE(67)] = 848,
  [SMALL_STATE(68)] = 855,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 869,
  [SMALL_STATE(71)] = 876,
  [SMALL_STATE(72)] = 883,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(22),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(18),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(72),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(67),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(11),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(15),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(64),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(30),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(52),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2), SHIFT_REPEAT(56),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_seg, 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_seg_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_seg_repeat1, 2), SHIFT_REPEAT(31),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2), SHIFT_REPEAT(41),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spread, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 5),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [220] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_corn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
